"""Mutation-site generator — 3 perturbation axes x 3 intensities (T1-2, SPEC eval-upgrade).

Renders the MockShop search page from ONE parameterized template and injects
DETERMINISTIC perturbations per cell: a clean reference + perception / action /
execution axes at light / medium / heavy intensity (10 cells). Fault schedules
use attempt counters and input-event anchoring — never Math.random — so every
run replays identically. Basis: StressWeb (arxiv 2604.16385) diagnostic
robustness axes + clean reference; WebArena's "too-clean environment
overestimates robustness" flaw (arxiv 2407.01502).

Held-out discipline: every cell derives only from the v1-style clean template;
the held-out mock site is never read or copied (a test locks this).

The real search field carries a `data-sb` ground-truth attribute for the
degradation runner's mid-task checkpoint. The agent's observer does NOT
enumerate that attribute, so it is invisible to the agent — instrumentation,
not a hint.

Usage:  .venv/Scripts/python tools/gen_mutation_sites.py
Writes  data/mock_sites/mutations/<cell>/index.html + manifest.json
Docs    data/mock_sites/PERTURBATIONS.md
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "mock_sites" / "mutations"

_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>MockShop — Search</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 760px; margin: 2rem auto; }
  header { border-bottom:2px solid #333; padding-bottom:.5rem; }
  #results li { margin:.4rem 0; }
  .decoy { color:#999; }
  .cookie-modal { position:fixed; inset:0; background:rgba(0,0,0,.5); display:flex;
    align-items:center; justify-content:center; z-index:10; }
  .cookie-modal .box { background:#fff; padding:2rem; border-radius:8px; }
</style>
</head>
<body>
<header><h1>MockShop</h1></header>
<!-- generated by tools/gen_mutation_sites.py — cell __CELL__ (do not hand-edit) -->
__PRE_FORM__
<form id="finder" onsubmit="return doSearch(event)">
  __INPUT__
  __BUTTON__
</form>
<ul id="results"></ul>
<script>
const CATALOG = [
  "Widget Pro 3000", "Widget Mini", "Gizmo Deluxe", "Gadget Standard",
  "Sprocket XL", "Cog Basic", "Widget Ultra", "Bolt Pack"
];
// deterministic fault schedule — no randomness, every run replays identically
const DELAY_MS = __DELAY__;
const FAIL_FIRST = __FAIL_FIRST__;
const REBUILD_ON_INPUT = __REBUILD__;
const SWAP_BUTTON_ON_INPUT = __SWAP__;
let attempt = 0, mutated = false;

function box() { return document.querySelector('[data-sb]'); }

function setStatus(text) {
  let s = document.getElementById('result-status');
  if (!s) {
    s = document.createElement('div');
    s.id = 'result-status';
    const ul = document.getElementById('results');
    ul.parentNode.insertBefore(s, ul);
  }
  s.textContent = text;
}

function renderHits(q) {
  const hits = CATALOG.filter(x => x.toLowerCase().includes(q));
  const ul = document.getElementById('results');
  ul.innerHTML = '';
  hits.forEach(function (name) {
    const li = document.createElement('li');
    li.className = 'result-item';
    li.textContent = name;
    ul.appendChild(li);
  });
  setStatus(hits.length + ' results for "' + q + '"');
}

function doSearch(e) {
  e.preventDefault();
  const q = (box() ? box().value : '').toLowerCase();
  // empty query must NOT dump the whole catalog (that would let a wrong-field
  // fill still "succeed" and mask the perception failure)
  if (!q) { setStatus('Enter a search term'); return false; }
  attempt++;
  if (FAIL_FIRST && attempt === 1) {
    setStatus('Server error (500). Please retry.');
    return false;
  }
  if (DELAY_MS > 0) { setTimeout(function () { renderHits(q); }, DELAY_MS); }
  else { renderHits(q); }
  return false;
}

// stale-snapshot fault: the nodes the agent already observed are REPLACED by
// new nodes (new ids, old data-aid handles die); the typed value is preserved
function rebuildForm() {
  const old = box();
  const ni = document.createElement('input');
  ni.type = 'text'; ni.id = 'sb1'; ni.name = 'q2';
  ni.setAttribute('aria-label', 'Search products');
  ni.setAttribute('data-sb', '1');
  ni.value = old.value;
  const ob = document.querySelector('#finder button, #finder [role=button], #finder span');
  const nb = document.createElement('button');
  nb.type = 'submit'; nb.id = 'btn1';
  nb.setAttribute('aria-label', 'Search');
  nb.textContent = 'Go';
  old.replaceWith(ni);
  if (ob) ob.replaceWith(nb);
}

// mid-task removal: the submit control that existed when the task started is
// gone by the time the agent clicks it; a differently-identified one appears
function swapButton() {
  const ob = document.getElementById('search-btn');
  if (!ob) return;
  const nb = document.createElement('button');
  nb.type = 'submit'; nb.id = 'resubmit';
  nb.setAttribute('aria-label', 'Search');
  nb.textContent = 'Submit';
  ob.replaceWith(nb);
}

// event-anchored (not timer-raced) mutation trigger: fires once, right after
// the first input lands in the real search field
document.addEventListener('input', function (ev) {
  if (!ev.target.hasAttribute || !ev.target.hasAttribute('data-sb')) return;
  if (mutated) return;
  mutated = true;
  if (REBUILD_ON_INPUT) setTimeout(rebuildForm, 0);
  if (SWAP_BUTTON_ON_INPUT) setTimeout(swapButton, 0);
});
</script>
</body>
</html>
"""

_COOKIE_MODAL = (
    '<div class="cookie-modal" id="cookie"><div class="box"><p>We use cookies.</p>'
    '<button id="accept-cookies" onclick="document.getElementById(\'cookie\').remove()">'
    "Accept</button></div></div>"
)
_DECOY = '<button class="decoy" id="fake-search" onclick="void 0">Search</button>'
_PROMO = ('<label>Promo code <input id="promo" name="promo" type="text" '
          'placeholder="Promo code"></label>')
_GHOST = '<input id="ghost" type="text" style="display:none" aria-label="Search products">'
_CLUTTER = "<p>Welcome to MockShop — deals every day. Browse our catalog below.</p>"

_INPUT_CLEAN = ('<input id="search-box" name="q" type="text" placeholder="Search products" '
                'aria-label="Search products" data-sb="1">')
_BUTTON_CLEAN = '<button id="search-btn" type="submit">Search</button>'


def _cell(axis: str, level: int, level_name: str, *, pre_form: str = "",
          input_html: str = _INPUT_CLEAN, button_html: str = _BUTTON_CLEAN,
          delay_ms: int = 0, fail_first: bool = False, rebuild_on_input: bool = False,
          swap_button_on_input: bool = False, perturbations: list[str] | None = None,
          design_intent: str = "", recoverable_in_principle: str = "") -> dict:
    return {
        "axis": axis, "level": level, "level_name": level_name,
        "pre_form": pre_form, "input": input_html, "button": button_html,
        "delay_ms": delay_ms, "fail_first": fail_first,
        "rebuild_on_input": rebuild_on_input, "swap_button_on_input": swap_button_on_input,
        "perturbations": perturbations or [],
        "design_intent": design_intent,
        "recoverable_in_principle": recoverable_in_principle,
    }


CELLS: dict[str, dict] = {
    "clean": _cell(
        "none", 0, "clean",
        design_intent="clean reference (StressWeb): fallback selectors hit directly, "
                      "0 repairs expected",
        recoverable_in_principle="n/a"),

    # --- perception axis: can the agent still IDENTIFY its targets? ---
    "perception-light": _cell(
        "perception", 1, "light",
        input_html=('<input id="qf" name="q" type="text" placeholder="Search products" '
                    'aria-label="Search products" data-sb="1">'),
        button_html='<button id="find-btn" type="submit">Find</button>',
        perturbations=["ids renamed (search-box->qf, search-btn->find-btn)",
                       "button text changed (Search->Find)"],
        design_intent="fallback selectors miss; semantic attributes intact -> repair recovers",
        recoverable_in_principle="yes — aria-label/placeholder/text still identify both targets"),
    "perception-medium": _cell(
        "perception", 2, "medium",
        pre_form=_CLUTTER + "\n" + _DECOY,
        input_html=('<input name="query" type="text" placeholder="Search products" '
                    'aria-label="Search products" data-sb="1">'),
        button_html='<button id="go2" type="submit" aria-label="Search">🔍</button>',
        perturbations=["input id removed", "submit button icon-only (aria-label kept)",
                       "decoy 'Search' button that does nothing",
                       "layout shifted (clutter before the form)"],
        design_intent="drift + deception; repair must pick the real control over the decoy",
        recoverable_in_principle="yes — decoy is heuristically excludable, semantics intact"),
    "perception-heavy": _cell(
        "perception", 3, "heavy",
        pre_form=_COOKIE_MODAL + "\n" + _PROMO + "\n" + _GHOST,
        input_html=('<input id="term-entry" name="term" type="text" '
                    'placeholder="Type here..." data-sb="1">'),
        button_html=('<div role="button" id="go-act" aria-label="Search" '
                     'onclick="return doSearch(event)">Go</div>'),
        perturbations=["cookie modal overlays the form", "submit is div[role=button]+onclick",
                       "real search field has NO search semantics (generic placeholder)",
                       "visible 'Promo code' bait field placed before the form",
                       "hidden ghost input with the search aria-label"],
        design_intent="a text/a11y-only matcher ties the bait field with the real one and "
                      "fills the wrong field -> empty query -> honest fail",
        recoverable_in_principle="yes — form proximity or visual grounding disambiguates"),

    # --- action axis: a11y-tree omission / stale snapshot ---
    "action-light": _cell(
        "action", 1, "light",
        input_html=('<input id="searchfield" name="q" type="text" '
                    'placeholder="Search products" data-sb="1">'),
        button_html='<button type="submit">Go</button>',
        perturbations=["ids renamed/removed", "submit has zero attributes (text 'Go' only)"],
        design_intent="thin a11y signal but still enumerable -> repair recovers",
        recoverable_in_principle="yes"),
    "action-medium": _cell(
        "action", 2, "medium",
        input_html=('<input id="sb0" name="term" type="text" '
                    'aria-label="Search products" data-sb="1">'),
        button_html='<button id="btn0" type="submit" aria-label="Search">Go</button>',
        rebuild_on_input=True,
        perturbations=["stale snapshot: first input event rebuilds the form nodes "
                       "(new ids sb1/btn1, observed data-aid handles die, value preserved)"],
        design_intent="the DOM the agent observed no longer exists at click time -> "
                      "re-observe + repair recovers",
        recoverable_in_principle="yes — a fresh observation sees the rebuilt nodes"),
    "action-heavy": _cell(
        "action", 3, "heavy",
        input_html=('<input id="entry" name="term" type="text" '
                    'aria-label="Search products" data-sb="1">'),
        button_html='<span id="go-plain" onclick="return doSearch(event)">Go</span>',
        perturbations=["a11y-tree omission: submit is a bare <span onclick> with no role — "
                       "it never appears in the observer's candidate enumeration"],
        design_intent="the submit control is invisible to an a11y-tree-only agent -> "
                      "repair cannot find it -> honest fail",
        recoverable_in_principle="yes — Enter in the single-input form implicit-submits"),

    # --- execution axis: environment faults while executing (clean identities) ---
    "execution-light": _cell(
        "execution", 1, "light",
        delay_ms=250,
        perturbations=["results render 250ms late (simulated XHR delay, inside the "
                       "agent's 400ms settle window)"],
        design_intent="benign latency; success expected with 0 repairs",
        recoverable_in_principle="n/a (non-destructive)"),
    "execution-medium": _cell(
        "execution", 2, "medium",
        delay_ms=250, swap_button_on_input=True,
        perturbations=["mid-task element removal: after the query is typed, #search-btn is "
                       "replaced by #resubmit (different id)", "250ms result delay"],
        design_intent="the planned click target vanished mid-task -> repair finds the "
                      "replacement = measurable mid-task recovery",
        recoverable_in_principle="yes — replacement button is enumerable"),
    "execution-heavy": _cell(
        "execution", 3, "heavy",
        delay_ms=250, swap_button_on_input=True, fail_first=True,
        perturbations=["mid-task element removal (as medium)",
                       "deterministic 500: first submit renders 'Server error (500)' and no "
                       "results; retries would succeed (attempt counter, no randomness)"],
        design_intent="selector recovery succeeds but the first submit 500s; Script Mode has "
                      "no retry loop -> honest fail (checkpoint pass, success fail)",
        recoverable_in_principle="yes — a single retry succeeds"),
}


def render_site(cell_id: str) -> str:
    c = CELLS[cell_id]
    html = _PAGE
    for tok, val in {
        "__CELL__": cell_id,
        "__PRE_FORM__": c["pre_form"],
        "__INPUT__": c["input"],
        "__BUTTON__": c["button"],
        "__DELAY__": str(c["delay_ms"]),
        "__FAIL_FIRST__": "true" if c["fail_first"] else "false",
        "__REBUILD__": "true" if c["rebuild_on_input"] else "false",
        "__SWAP__": "true" if c["swap_button_on_input"] else "false",
    }.items():
        html = html.replace(tok, val)
    return html


def manifest() -> dict:
    return {
        "generated_by": "tools/gen_mutation_sites.py",
        "basis": "StressWeb (arxiv 2604.16385) axes x intensity + clean reference; "
                 "WebArena too-clean-environment flaw (arxiv 2407.01502)",
        "determinism": "no Math.random; attempt-counter fault schedule; input-event-anchored "
                       "mutations (setTimeout 0), not timer races",
        "heldout_note": "cells derive only from the v1-style clean template; the held-out "
                        "mock site is never read (locked by test)",
        "cells": {
            cid: {k: c[k] for k in ("axis", "level", "level_name", "perturbations",
                                    "design_intent", "recoverable_in_principle")}
            for cid, c in CELLS.items()
        },
    }


def generate() -> None:
    for cell_id in CELLS:
        d = OUT / cell_id
        d.mkdir(parents=True, exist_ok=True)
        with open(d / "index.html", "w", encoding="utf-8", newline="\n") as fh:
            fh.write(render_site(cell_id))
    with open(OUT / "manifest.json", "w", encoding="utf-8", newline="\n") as fh:
        json.dump(manifest(), fh, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    generate()
    print(f"wrote {len(CELLS)} cells + manifest.json under {OUT}")
